version: '3'

services:

  frontend:
    image: energy-utility-frontend
    container_name: energy-utility-frontend-container
    ports:
       - "80:80"
       - "443:443"
#    volumes:
#       - './devcerts:/etc/nginx/volume_certs'
#    extra_hosts:
#      - "local.example:127.0.0.1"

  envoy:
    image: envoyproxy/envoy-dev:b145180d17cac80aa5f9a7801429d52017fea6d1
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8081:8081"